apiVersion: v1
kind: Service
metadata:
  name: producer-svc
spec:
  selector:
    app: producer-svc
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-svc
spec:
  selector:
    matchLabels:
      app: producer-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: producer-svc
    spec:
      containers:
        - name: producer-svc
          image: mertcakmak2/k8s-kafka-producer
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: kafka-service
              value: "kafka-service"